-- ============================================================================
-- SUPABASE PUBLIC SCHEMA DUMP
-- Generated: 2026-01-18
-- ============================================================================

-- ============================================================================
-- EXTENSIONS (pgvector for embeddings)
-- ============================================================================
-- Note: The vector extension is enabled for embedding support

-- ============================================================================
-- TABLES
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Core User & Messaging Tables
-- ----------------------------------------------------------------------------

CREATE TABLE public.profiles (
  id uuid NOT NULL,
  first_name text,
  last_name text,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  business_name text,
  phone text,
  profile_url text,
  account_code text,
  fcm_token text,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);

CREATE TABLE public.topic (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  title text NOT NULL,
  summary text NOT NULL,
  logo_url text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  display_order smallint,
  call_to_action_title text,
  CONSTRAINT topic_pkey PRIMARY KEY (id)
);
COMMENT ON TABLE public.topic IS 'Message topics';

CREATE TABLE public.message (
  content text NOT NULL,
  viewed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid NOT NULL DEFAULT auth.uid(),
  topic_id bigint NOT NULL,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  CONSTRAINT message_pkey PRIMARY KEY (id),
  CONSTRAINT public_message_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT public_message_topic_id_fkey FOREIGN KEY (topic_id) REFERENCES public.topic(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.reply (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  message_id uuid,
  content text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT reply_pkey PRIMARY KEY (id),
  CONSTRAINT reply_message_id_fkey FOREIGN KEY (message_id) REFERENCES public.message(id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT reply_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id) ON UPDATE CASCADE ON DELETE CASCADE
);
COMMENT ON TABLE public.reply IS 'Message replies';

CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  body text NOT NULL,
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);

CREATE TABLE public.device_tokens (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  user_id uuid,
  device_token text,
  platform text,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT device_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT unique_user_device_token UNIQUE (user_id, device_token),
  CONSTRAINT device_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);

-- ----------------------------------------------------------------------------
-- Articles & Content Tables
-- ----------------------------------------------------------------------------

CREATE TABLE public.categorys (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  category text,
  display_order smallint,
  CONSTRAINT categorys_pkey PRIMARY KEY (id)
);

CREATE TABLE public.articles (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  title text,
  banner text,
  summary text,
  content text,
  category_id bigint,
  CONSTRAINT articles_pkey PRIMARY KEY (id),
  CONSTRAINT public_articles_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categorys(id) ON UPDATE CASCADE ON DELETE CASCADE
);
COMMENT ON TABLE public.articles IS 'Articles';

CREATE TABLE public.content_block (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  article_id bigint NOT NULL,
  content_type text NOT NULL,
  content text NOT NULL,
  display_order smallint NOT NULL,
  CONSTRAINT content_block_pkey PRIMARY KEY (id),
  CONSTRAINT public_content_block_article_id_fkey FOREIGN KEY (article_id) REFERENCES public.articles(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.services (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  title text,
  content text,
  image text,
  display_order smallint,
  subhead text,
  call_to_action text,
  c2a_navigate_to_page text,
  CONSTRAINT services_pkey PRIMARY KEY (id)
);
COMMENT ON TABLE public.services IS 'Business Services';

-- ----------------------------------------------------------------------------
-- Customer & Cost Calculator Tables
-- ----------------------------------------------------------------------------

CREATE TABLE public.customer (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  account_code text,
  first_name text,
  last_name text,
  email text,
  business_name text,
  phone text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT customer_pkey PRIMARY KEY (id)
);

CREATE TABLE public.cost_calculator (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  first_name text,
  last_name text,
  email text,
  phone text,
  uid uuid DEFAULT gen_random_uuid(),
  status text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  service_type text,
  app_description text,
  CONSTRAINT cost_calculator_pkey PRIMARY KEY (id)
);
COMMENT ON TABLE public.cost_calculator IS 'Cost Calculator Users';
COMMENT ON COLUMN public.cost_calculator.service_type IS 'Type of service';
COMMENT ON COLUMN public.cost_calculator.app_description IS 'Short description of the application';

-- ----------------------------------------------------------------------------
-- Project & Requirements Management Tables
-- ----------------------------------------------------------------------------

CREATE TABLE public.projects (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  name character varying(255) NOT NULL,
  description text,
  version character varying(50) DEFAULT '1.0.0'::character varying,
  stakeholders text[],
  problem_statement text,
  business_objectives text[],
  success_criteria text[],
  assumptions text[],
  constraints text[],
  status character varying(50) DEFAULT 'active'::character varying,
  keywords text[],
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT projects_pkey PRIMARY KEY (id),
  CONSTRAINT projects_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);

CREATE TABLE public.project_user_types (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  name character varying(255) NOT NULL,
  description text,
  permissions text[],
  responsibilities text[],
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT project_user_types_pkey PRIMARY KEY (id),
  CONSTRAINT project_user_types_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE
);

CREATE TABLE public.project_glossary (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  term character varying(255) NOT NULL,
  definition text NOT NULL,
  aliases text[],
  context character varying(500),
  usage_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT project_glossary_pkey PRIMARY KEY (id),
  CONSTRAINT project_glossary_project_id_term_key UNIQUE (project_id, term),
  CONSTRAINT project_glossary_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE
);

CREATE TABLE public.requirement_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying(100) NOT NULL,
  description text,
  color character varying(7),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT requirement_categories_pkey PRIMARY KEY (id),
  CONSTRAINT requirement_categories_name_key UNIQUE (name)
);

CREATE TABLE public.priority_levels (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying(20) NOT NULL,
  level integer NOT NULL,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT priority_levels_pkey PRIMARY KEY (id),
  CONSTRAINT priority_levels_name_key UNIQUE (name),
  CONSTRAINT priority_levels_level_key UNIQUE (level)
);

CREATE TABLE public.requirements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  requirement_id character varying(50) NOT NULL,
  title character varying(500) NOT NULL,
  description text NOT NULL,
  category_id uuid,
  priority_id uuid,
  status character varying(50) DEFAULT 'draft'::character varying,
  user_story text,
  complexity character varying(20),
  estimated_effort character varying(50),
  content_hash text,
  context_summary text,
  related_concepts text[],
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT requirements_pkey PRIMARY KEY (id),
  CONSTRAINT requirements_project_id_requirement_id_key UNIQUE (project_id, requirement_id),
  CONSTRAINT requirements_requirement_id_check CHECK (requirement_id::text ~ '^[A-Z]{2,5}-[0-9]{3,4}$'::text),
  CONSTRAINT requirements_status_check CHECK (status::text = ANY (ARRAY['draft', 'approved', 'in_development', 'complete', 'deprecated']::text[])),
  CONSTRAINT requirements_complexity_check CHECK (complexity::text = ANY (ARRAY['Low', 'Medium', 'High']::text[])),
  CONSTRAINT requirements_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE,
  CONSTRAINT requirements_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.requirement_categories(id),
  CONSTRAINT requirements_priority_id_fkey FOREIGN KEY (priority_id) REFERENCES public.priority_levels(id)
);

CREATE TABLE public.tags (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  name character varying(100) NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT tags_pkey PRIMARY KEY (id),
  CONSTRAINT tags_project_id_name_key UNIQUE (project_id, name),
  CONSTRAINT tags_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE
);
COMMENT ON TABLE public.tags IS 'Stores unique, project-specific tags for categorizing requirements.';
COMMENT ON COLUMN public.tags.project_id IS 'The project this tag belongs to.';
COMMENT ON COLUMN public.tags.name IS 'The name of the tag (e.g., "API", "Authentication").';

CREATE TABLE public.requirement_tags (
  requirement_id uuid NOT NULL,
  tag_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT requirement_tags_pkey PRIMARY KEY (requirement_id, tag_id),
  CONSTRAINT requirement_tags_requirement_id_fkey FOREIGN KEY (requirement_id) REFERENCES public.requirements(id) ON DELETE CASCADE,
  CONSTRAINT requirement_tags_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES public.tags(id) ON DELETE CASCADE
);
COMMENT ON TABLE public.requirement_tags IS 'Links requirements to their associated tags.';

CREATE TABLE public.acceptance_criteria (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  requirement_id uuid NOT NULL,
  criteria_id character varying(50) NOT NULL,
  description text NOT NULL,
  given_condition text,
  when_action text,
  then_outcome text,
  priority integer DEFAULT 1,
  testability_score double precision,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT acceptance_criteria_pkey PRIMARY KEY (id),
  CONSTRAINT acceptance_criteria_requirement_id_criteria_id_key UNIQUE (requirement_id, criteria_id),
  CONSTRAINT acceptance_criteria_criteria_id_check CHECK (criteria_id::text ~ '^AC-[0-9]{3,4}$'::text),
  CONSTRAINT acceptance_criteria_testability_score_check CHECK (testability_score >= 0 AND testability_score <= 1),
  CONSTRAINT acceptance_criteria_requirement_id_fkey FOREIGN KEY (requirement_id) REFERENCES public.requirements(id) ON DELETE CASCADE
);

CREATE TABLE public.business_rules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  requirement_id uuid NOT NULL,
  rule_text text NOT NULL,
  rule_type character varying(100),
  rule_pattern character varying(200),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT business_rules_pkey PRIMARY KEY (id),
  CONSTRAINT business_rules_requirement_id_fkey FOREIGN KEY (requirement_id) REFERENCES public.requirements(id) ON DELETE CASCADE
);

CREATE TABLE public.data_requirements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  requirement_id uuid NOT NULL,
  direction character varying(20) NOT NULL,
  name character varying(255) NOT NULL,
  data_type character varying(100) NOT NULL,
  required boolean DEFAULT false,
  format_specification text,
  constraints_rules text,
  validation_rules jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT data_requirements_pkey PRIMARY KEY (id),
  CONSTRAINT data_requirements_direction_check CHECK (direction::text = ANY (ARRAY['input', 'output']::text[])),
  CONSTRAINT data_requirements_requirement_id_fkey FOREIGN KEY (requirement_id) REFERENCES public.requirements(id) ON DELETE CASCADE
);

CREATE TABLE public.workflow_steps (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  requirement_id uuid NOT NULL,
  step_number integer NOT NULL,
  action_description text NOT NULL,
  actor character varying(255),
  system_response text,
  alternative_flows text[],
  step_complexity double precision,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT workflow_steps_pkey PRIMARY KEY (id),
  CONSTRAINT workflow_steps_requirement_id_step_number_key UNIQUE (requirement_id, step_number),
  CONSTRAINT workflow_steps_step_complexity_check CHECK (step_complexity >= 0 AND step_complexity <= 1),
  CONSTRAINT workflow_steps_requirement_id_fkey FOREIGN KEY (requirement_id) REFERENCES public.requirements(id) ON DELETE CASCADE
);

CREATE TABLE public.requirement_relationships (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  source_requirement_id uuid NOT NULL,
  target_requirement_id uuid NOT NULL,
  relationship_type character varying(50) NOT NULL,
  strength double precision DEFAULT 1.0,
  description text,
  auto_detected boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT requirement_relationships_pkey PRIMARY KEY (id),
  CONSTRAINT requirement_relationships_source_requirement_id_target_requ_key UNIQUE (source_requirement_id, target_requirement_id, relationship_type),
  CONSTRAINT requirement_relationships_check CHECK (source_requirement_id <> target_requirement_id),
  CONSTRAINT requirement_relationships_relationship_type_check CHECK (relationship_type::text = ANY (ARRAY['depends_on', 'conflicts_with', 'extends', 'relates_to', 'blocks', 'implements']::text[])),
  CONSTRAINT requirement_relationships_strength_check CHECK (strength >= 0 AND strength <= 1),
  CONSTRAINT requirement_relationships_source_requirement_id_fkey FOREIGN KEY (source_requirement_id) REFERENCES public.requirements(id) ON DELETE CASCADE,
  CONSTRAINT requirement_relationships_target_requirement_id_fkey FOREIGN KEY (target_requirement_id) REFERENCES public.requirements(id) ON DELETE CASCADE
);

CREATE TABLE public.integration_requirements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  requirement_id uuid NOT NULL,
  system_name character varying(255) NOT NULL,
  integration_type character varying(100) NOT NULL,
  direction character varying(20) NOT NULL,
  data_format character varying(100),
  frequency character varying(100),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT integration_requirements_pkey PRIMARY KEY (id),
  CONSTRAINT integration_requirements_direction_check CHECK (direction::text = ANY (ARRAY['inbound', 'outbound', 'bidirectional']::text[])),
  CONSTRAINT integration_requirements_requirement_id_fkey FOREIGN KEY (requirement_id) REFERENCES public.requirements(id) ON DELETE CASCADE
);

CREATE TABLE public.requirement_risks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  requirement_id uuid NOT NULL,
  risk_description text NOT NULL,
  probability character varying(20),
  impact character varying(20),
  mitigation_strategy text,
  status character varying(20) DEFAULT 'identified'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT requirement_risks_pkey PRIMARY KEY (id),
  CONSTRAINT requirement_risks_probability_check CHECK (probability::text = ANY (ARRAY['Low', 'Medium', 'High']::text[])),
  CONSTRAINT requirement_risks_impact_check CHECK (impact::text = ANY (ARRAY['Low', 'Medium', 'High']::text[])),
  CONSTRAINT requirement_risks_status_check CHECK (status::text = ANY (ARRAY['identified', 'mitigating', 'resolved', 'accepted']::text[])),
  CONSTRAINT requirement_risks_requirement_id_fkey FOREIGN KEY (requirement_id) REFERENCES public.requirements(id) ON DELETE CASCADE
);

CREATE TABLE public.requirement_changes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  requirement_id uuid NOT NULL,
  change_type character varying(50) NOT NULL,
  field_changed character varying(100),
  old_value text,
  new_value text,
  change_reason text,
  changed_by uuid,
  ai_suggested boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT requirement_changes_pkey PRIMARY KEY (id),
  CONSTRAINT requirement_changes_requirement_id_fkey FOREIGN KEY (requirement_id) REFERENCES public.requirements(id) ON DELETE CASCADE,
  CONSTRAINT requirement_changes_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES auth.users(id)
);

-- ----------------------------------------------------------------------------
-- AI & Embeddings Tables
-- ----------------------------------------------------------------------------

CREATE TABLE public.content_embeddings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  content_type character varying(50) NOT NULL,
  content_id uuid NOT NULL,
  project_id uuid NOT NULL,
  embedding vector NOT NULL,
  content_text text NOT NULL,
  content_hash text NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT content_embeddings_pkey PRIMARY KEY (id),
  CONSTRAINT content_embeddings_content_type_content_id_key UNIQUE (content_type, content_id),
  CONSTRAINT content_embeddings_content_type_check CHECK (content_type::text = ANY (ARRAY['project', 'requirement', 'criteria', 'rule', 'workflow', 'glossary']::text[])),
  CONSTRAINT content_embeddings_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE,
  CONSTRAINT content_embeddings_requirement_fkey FOREIGN KEY (content_id) REFERENCES public.requirements(id) ON DELETE CASCADE
);

CREATE TABLE public.ai_interactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  requirement_id uuid,
  interaction_type character varying(50) NOT NULL,
  user_prompt text NOT NULL,
  ai_response text NOT NULL,
  confidence_score double precision,
  context_used jsonb DEFAULT '{}'::jsonb,
  tokens_used integer,
  model_version character varying(50),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_interactions_pkey PRIMARY KEY (id),
  CONSTRAINT ai_interactions_confidence_score_check CHECK (confidence_score >= 0 AND confidence_score <= 1),
  CONSTRAINT ai_interactions_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE,
  CONSTRAINT ai_interactions_requirement_id_fkey FOREIGN KEY (requirement_id) REFERENCES public.requirements(id) ON DELETE SET NULL
);

CREATE TABLE public.ai_insights (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  requirement_id uuid,
  insight_type character varying(100) NOT NULL,
  title character varying(500) NOT NULL,
  description text NOT NULL,
  confidence_score double precision NOT NULL,
  status character varying(50) DEFAULT 'pending'::character varying,
  supporting_evidence jsonb DEFAULT '{}'::jsonb,
  impact_score double precision,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_insights_pkey PRIMARY KEY (id),
  CONSTRAINT ai_insights_confidence_score_check CHECK (confidence_score >= 0 AND confidence_score <= 1),
  CONSTRAINT ai_insights_status_check CHECK (status::text = ANY (ARRAY['pending', 'accepted', 'rejected', 'implemented']::text[])),
  CONSTRAINT ai_insights_impact_score_check CHECK (impact_score >= 0 AND impact_score <= 1),
  CONSTRAINT ai_insights_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE,
  CONSTRAINT ai_insights_requirement_id_fkey FOREIGN KEY (requirement_id) REFERENCES public.requirements(id) ON DELETE CASCADE
);

-- ----------------------------------------------------------------------------
-- Blog System Tables (sws2026_*)
-- ----------------------------------------------------------------------------

CREATE TABLE public.sws2026_blog_authors (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  name character varying(255) NOT NULL,
  slug character varying(255) NOT NULL,
  bio text,
  avatar_url text,
  social_links jsonb DEFAULT '{}'::jsonb,
  expertise text[],
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  can_export boolean DEFAULT false,
  CONSTRAINT sws2026_blog_authors_pkey PRIMARY KEY (id),
  CONSTRAINT sws2026_blog_authors_slug_key UNIQUE (slug),
  CONSTRAINT sws2026_blog_authors_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
COMMENT ON TABLE public.sws2026_blog_authors IS 'Blog post authors with E-E-A-T signals';

CREATE TABLE public.sws2026_blog_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying(255) NOT NULL,
  slug character varying(255) NOT NULL,
  description text,
  meta_title character varying(60),
  meta_description character varying(160),
  color character varying(7),
  icon text,
  display_order smallint DEFAULT 0,
  show_in_nav boolean DEFAULT true,
  show_on_homepage boolean DEFAULT true,
  parent_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  subtitle text,
  CONSTRAINT sws2026_blog_categories_pkey PRIMARY KEY (id),
  CONSTRAINT sws2026_blog_categories_slug_key UNIQUE (slug),
  CONSTRAINT sws2026_blog_categories_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.sws2026_blog_categories(id)
);
COMMENT ON TABLE public.sws2026_blog_categories IS 'Blog categories with display ordering';

CREATE TABLE public.sws2026_blog_tags (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying(100) NOT NULL,
  slug character varying(100) NOT NULL,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sws2026_blog_tags_pkey PRIMARY KEY (id),
  CONSTRAINT sws2026_blog_tags_slug_key UNIQUE (slug)
);
COMMENT ON TABLE public.sws2026_blog_tags IS 'Blog post tags for granular categorization';

CREATE TABLE public.sws2026_surveys (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying(255) NOT NULL,
  slug character varying(255) NOT NULL,
  description text,
  json_definition jsonb NOT NULL DEFAULT '{}'::jsonb,
  status character varying(20) DEFAULT 'active'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sws2026_surveys_pkey PRIMARY KEY (id),
  CONSTRAINT sws2026_surveys_slug_key UNIQUE (slug),
  CONSTRAINT sws2026_surveys_status_check CHECK (status::text = ANY (ARRAY['active', 'inactive']::text[]))
);

CREATE TABLE public.sws2026_blog_posts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title character varying(255) NOT NULL,
  slug character varying(255) NOT NULL,
  subtitle text,
  excerpt text,
  content text NOT NULL,
  featured_image text,
  featured_image_alt text,
  og_image text,
  author_id uuid NOT NULL,
  category_id uuid NOT NULL,
  status character varying(20) DEFAULT 'draft'::character varying,
  published_at timestamp with time zone,
  scheduled_for timestamp with time zone,
  is_featured boolean DEFAULT false,
  featured_order smallint,
  meta_title character varying(60),
  meta_description character varying(160),
  canonical_url text,
  primary_keyword character varying(100),
  secondary_keywords text[],
  ai_summary text,
  key_takeaways text[],
  definitive_statements text[],
  questions_answered text[],
  entities jsonb DEFAULT '[]'::jsonb,
  topic_cluster character varying(100),
  content_type character varying(50),
  expertise_level character varying(20),
  last_verified_at timestamp with time zone,
  sources jsonb DEFAULT '[]'::jsonb,
  read_time_minutes smallint,
  word_count integer,
  view_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  survey_id uuid,
  enquiry_cta_title character varying(100),
  calendly_enabled boolean DEFAULT false,
  calendly_event_type_uri text,
  calendly_cta_title character varying(255),
  calendly_cta_description text,
  calendly_scheduling_url text,
  is_lead_article boolean DEFAULT false,
  CONSTRAINT sws2026_blog_posts_pkey PRIMARY KEY (id),
  CONSTRAINT sws2026_blog_posts_slug_key UNIQUE (slug),
  CONSTRAINT sws2026_blog_posts_status_check CHECK (status::text = ANY (ARRAY['draft', 'scheduled', 'published', 'archived']::text[])),
  CONSTRAINT sws2026_blog_posts_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.sws2026_blog_authors(id),
  CONSTRAINT sws2026_blog_posts_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.sws2026_blog_categories(id),
  CONSTRAINT sws2026_blog_posts_survey_id_fkey FOREIGN KEY (survey_id) REFERENCES public.sws2026_surveys(id) ON DELETE SET NULL
);
COMMENT ON TABLE public.sws2026_blog_posts IS 'Blog posts with comprehensive SEO and AI optimization fields';
COMMENT ON COLUMN public.sws2026_blog_posts.calendly_enabled IS 'Whether Calendly booking is enabled for this post';
COMMENT ON COLUMN public.sws2026_blog_posts.calendly_event_type_uri IS 'The Calendly event type URI for this post';
COMMENT ON COLUMN public.sws2026_blog_posts.is_lead_article IS 'Lead articles are hidden from all public listings but accessible via direct URL';

CREATE TABLE public.sws2026_blog_post_tags (
  post_id uuid NOT NULL,
  tag_id uuid NOT NULL,
  CONSTRAINT sws2026_blog_post_tags_pkey PRIMARY KEY (post_id, tag_id),
  CONSTRAINT sws2026_blog_post_tags_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.sws2026_blog_posts(id) ON DELETE CASCADE,
  CONSTRAINT sws2026_blog_post_tags_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES public.sws2026_blog_tags(id) ON DELETE CASCADE
);
COMMENT ON TABLE public.sws2026_blog_post_tags IS 'Many-to-many relationship between posts and tags';

CREATE TABLE public.sws2026_blog_faqs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  post_id uuid NOT NULL,
  question text NOT NULL,
  answer text NOT NULL,
  display_order smallint DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sws2026_blog_faqs_pkey PRIMARY KEY (id),
  CONSTRAINT sws2026_blog_faqs_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.sws2026_blog_posts(id) ON DELETE CASCADE
);
COMMENT ON TABLE public.sws2026_blog_faqs IS 'FAQs for blog posts - generates FAQ schema for SEO/AI';

CREATE TABLE public.sws2026_blog_related_posts (
  post_id uuid NOT NULL,
  related_post_id uuid NOT NULL,
  relevance_score double precision DEFAULT 1.0,
  is_manual boolean DEFAULT false,
  CONSTRAINT sws2026_blog_related_posts_pkey PRIMARY KEY (post_id, related_post_id),
  CONSTRAINT sws2026_blog_related_posts_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.sws2026_blog_posts(id) ON DELETE CASCADE,
  CONSTRAINT sws2026_blog_related_posts_related_post_id_fkey FOREIGN KEY (related_post_id) REFERENCES public.sws2026_blog_posts(id) ON DELETE CASCADE
);
COMMENT ON TABLE public.sws2026_blog_related_posts IS 'Related posts for internal linking';

CREATE TABLE public.sws2026_blog_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  key character varying(100) NOT NULL,
  value jsonb NOT NULL,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sws2026_blog_settings_pkey PRIMARY KEY (id),
  CONSTRAINT sws2026_blog_settings_key_key UNIQUE (key)
);
COMMENT ON TABLE public.sws2026_blog_settings IS 'Global blog configuration settings';

CREATE TABLE public.sws2026_blog_post_embeddings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  post_id uuid NOT NULL,
  embedding vector,
  content_hash text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sws2026_blog_post_embeddings_pkey PRIMARY KEY (id),
  CONSTRAINT sws2026_blog_post_embeddings_post_id_key UNIQUE (post_id),
  CONSTRAINT sws2026_blog_post_embeddings_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.sws2026_blog_posts(id) ON DELETE CASCADE
);
COMMENT ON TABLE public.sws2026_blog_post_embeddings IS 'Vector embeddings for semantic blog search';

CREATE TABLE public.sws2026_blog_writer_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  author_id uuid NOT NULL,
  current_step integer NOT NULL DEFAULT 1,
  status character varying(20) DEFAULT 'in_progress'::character varying,
  working_title character varying(255),
  transcript text,
  target_word_count integer,
  extracted_material jsonb DEFAULT '{}'::jsonb,
  outline jsonb DEFAULT '[]'::jsonb,
  sections jsonb DEFAULT '[]'::jsonb,
  compiled_content text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sws2026_blog_writer_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT sws2026_blog_writer_sessions_status_check CHECK (status::text = ANY (ARRAY['in_progress', 'completed', 'abandoned']::text[])),
  CONSTRAINT sws2026_blog_writer_sessions_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.sws2026_blog_authors(id) ON DELETE CASCADE
);
COMMENT ON TABLE public.sws2026_blog_writer_sessions IS 'Blog writer sessions for video-to-blog workflow';

-- ----------------------------------------------------------------------------
-- Contact & Newsletter Tables
-- ----------------------------------------------------------------------------

CREATE TABLE public.sws2026_newsletter_subscribers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email character varying(255) NOT NULL,
  name character varying(255),
  status character varying(20) DEFAULT 'active'::character varying,
  source character varying(50),
  subscribed_at timestamp with time zone DEFAULT now(),
  unsubscribed_at timestamp with time zone,
  CONSTRAINT sws2026_newsletter_subscribers_pkey PRIMARY KEY (id),
  CONSTRAINT sws2026_newsletter_subscribers_email_key UNIQUE (email),
  CONSTRAINT sws2026_newsletter_subscribers_status_check CHECK (status::text = ANY (ARRAY['active', 'unsubscribed', 'bounced']::text[]))
);
COMMENT ON TABLE public.sws2026_newsletter_subscribers IS 'Newsletter email subscribers';

CREATE TABLE public.sws2026_contact_submissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying(255) NOT NULL,
  email character varying(255) NOT NULL,
  company character varying(255),
  phone character varying(50),
  message text NOT NULL,
  status character varying(20) DEFAULT 'new'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sws2026_contact_submissions_pkey PRIMARY KEY (id),
  CONSTRAINT sws2026_contact_submissions_status_check CHECK (status::text = ANY (ARRAY['new', 'read', 'replied', 'archived']::text[]))
);
COMMENT ON TABLE public.sws2026_contact_submissions IS 'Contact form submissions';

CREATE TABLE public.sws2026_enquiries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  survey_id uuid NOT NULL,
  post_id uuid,
  response_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  respondent_email character varying(255),
  respondent_name character varying(255),
  status character varying(20) DEFAULT 'new'::character varying,
  source_url text,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sws2026_enquiries_pkey PRIMARY KEY (id),
  CONSTRAINT sws2026_enquiries_status_check CHECK (status::text = ANY (ARRAY['new', 'read', 'archived']::text[])),
  CONSTRAINT sws2026_enquiries_survey_id_fkey FOREIGN KEY (survey_id) REFERENCES public.sws2026_surveys(id) ON DELETE CASCADE,
  CONSTRAINT sws2026_enquiries_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.sws2026_blog_posts(id) ON DELETE SET NULL
);

-- ----------------------------------------------------------------------------
-- Calendly & Chat Tables
-- ----------------------------------------------------------------------------

CREATE TABLE public.sws2026_calendly_bookings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  post_id uuid,
  calendly_event_uri text,
  event_type_uri text NOT NULL,
  event_start_time timestamp with time zone NOT NULL,
  invitee_name character varying(255) NOT NULL,
  invitee_email character varying(255) NOT NULL,
  invitee_phone character varying(50),
  invitee_company character varying(255),
  invitee_message text,
  status character varying(50) DEFAULT 'pending'::character varying,
  source_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sws2026_calendly_bookings_pkey PRIMARY KEY (id),
  CONSTRAINT sws2026_calendly_bookings_status_check CHECK (status::text = ANY (ARRAY['pending', 'confirmed', 'cancelled', 'completed']::text[])),
  CONSTRAINT sws2026_calendly_bookings_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.sws2026_blog_posts(id) ON DELETE SET NULL
);
COMMENT ON TABLE public.sws2026_calendly_bookings IS 'Calendly booking records linked to blog posts';

CREATE TABLE public.sws2026_live_chat_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  is_online boolean DEFAULT false,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sws2026_live_chat_settings_pkey PRIMARY KEY (id)
);

CREATE TABLE public.sws2026_chat_conversations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  visitor_id text NOT NULL,
  visitor_name text,
  post_id uuid,
  source_url text,
  status text DEFAULT 'active'::text,
  last_message_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  visitor_ip text,
  visitor_email text,
  CONSTRAINT sws2026_chat_conversations_pkey PRIMARY KEY (id),
  CONSTRAINT sws2026_chat_conversations_status_check CHECK (status = ANY (ARRAY['active', 'closed', 'archived'])),
  CONSTRAINT sws2026_chat_conversations_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.sws2026_blog_posts(id)
);

CREATE TABLE public.sws2026_chat_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_id uuid,
  sender_type text NOT NULL,
  content text NOT NULL,
  is_read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sws2026_chat_messages_pkey PRIMARY KEY (id),
  CONSTRAINT sws2026_chat_messages_sender_type_check CHECK (sender_type = ANY (ARRAY['visitor', 'admin'])),
  CONSTRAINT sws2026_chat_messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.sws2026_chat_conversations(id) ON DELETE CASCADE
);

CREATE TABLE public.sws2026_blocked_ips (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ip_address text NOT NULL,
  reason text,
  blocked_by text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sws2026_blocked_ips_pkey PRIMARY KEY (id),
  CONSTRAINT sws2026_blocked_ips_ip_address_key UNIQUE (ip_address)
);

-- ----------------------------------------------------------------------------
-- Media & Help Tables
-- ----------------------------------------------------------------------------

CREATE TABLE public.sws2026_media (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  filename character varying(255) NOT NULL,
  original_filename character varying(255) NOT NULL,
  storage_path text NOT NULL,
  public_url text NOT NULL,
  file_type character varying(50) NOT NULL,
  mime_type character varying(100) NOT NULL,
  file_size bigint NOT NULL,
  width integer,
  height integer,
  duration integer,
  alt_text text,
  caption text,
  tags text[] DEFAULT '{}'::text[],
  metadata jsonb DEFAULT '{}'::jsonb,
  uploaded_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sws2026_media_pkey PRIMARY KEY (id),
  CONSTRAINT sws2026_media_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES auth.users(id)
);

CREATE TABLE public.sws2026_help_options (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  text character varying(255) NOT NULL,
  description text,
  post_id uuid NOT NULL,
  display_order smallint DEFAULT 0,
  is_active boolean DEFAULT true,
  icon character varying(100),
  color character varying(7),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sws2026_help_options_pkey PRIMARY KEY (id),
  CONSTRAINT sws2026_help_options_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.sws2026_blog_posts(id) ON DELETE CASCADE
);
COMMENT ON TABLE public.sws2026_help_options IS 'Help options for the lead capture helper section on homepage';

-- ----------------------------------------------------------------------------
-- Utility Tables
-- ----------------------------------------------------------------------------

CREATE TABLE public.scratch (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  data text,
  CONSTRAINT scratch_pkey PRIMARY KEY (id)
);

CREATE TABLE public.tasks (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid DEFAULT gen_random_uuid(),
  task_name text,
  CONSTRAINT tasks_pkey PRIMARY KEY (id)
);


-- ============================================================================
-- VIEWS
-- ============================================================================

CREATE OR REPLACE VIEW public.all_messages AS
SELECT
  m.id AS message_id,
  m.content,
  m.viewed_at,
  m.created_at AS message_created_at,
  m.created_by,
  m.topic_id AS message_topic_id,
  p.id AS profile_id,
  p.first_name,
  p.last_name,
  p.updated_at AS profile_updated_at,
  p.created_at AS profile_created_at,
  p.business_name,
  p.phone,
  p.profile_url,
  t.id AS topic_id,
  t.title,
  t.summary,
  t.logo_url,
  t.created_at AS topic_created_at,
  t.display_order,
  t.call_to_action_title
FROM message m
JOIN profiles p ON m.created_by = p.id
JOIN topic t ON m.topic_id = t.id;

CREATE OR REPLACE VIEW public.vw_messages AS
SELECT
  m.id AS message_id,
  m.content,
  m.viewed_at,
  m.created_at AS message_created_at,
  m.created_by,
  m.topic_id AS message_topic_id,
  p.id AS profile_id,
  p.first_name,
  p.last_name,
  p.updated_at AS profile_updated_at,
  p.created_at AS profile_created_at,
  p.business_name,
  p.phone,
  p.profile_url,
  t.id AS topic_id,
  t.title,
  t.summary,
  t.logo_url,
  t.created_at AS topic_created_at,
  t.display_order,
  t.call_to_action_title
FROM message m
JOIN profiles p ON m.created_by = p.id
JOIN topic t ON m.topic_id = t.id;

CREATE OR REPLACE VIEW public.vw_replies AS
SELECT
  m.id AS message_id,
  r.id AS reply_id,
  r.content AS reply_content,
  r.created_at AS reply_created_at,
  r.created_by AS reply_creator_id,
  p.first_name,
  p.last_name,
  p.profile_url
FROM message m
JOIN reply r ON m.id = r.message_id
JOIN profiles p ON p.id = r.created_by;

CREATE OR REPLACE VIEW public.requirement_ai_context AS
SELECT
  r.id,
  r.project_id,
  r.requirement_id::text AS requirement_id,
  r.title::text AS title,
  r.description,
  COALESCE(r.user_story, ''::text) AS user_story,
  COALESCE(rc.name::text, 'Uncategorized'::text) AS category_name,
  COALESCE(pl.name::text, 'No Priority'::text) AS priority_name,
  COALESCE(pl.level, 0) AS priority_level,
  COALESCE(array_agg(t.name) FILTER (WHERE t.name IS NOT NULL), '{}'::character varying[]) AS tags,
  concat_ws(' | '::text,
    NULLIF(r.title::text, ''::text),
    NULLIF(r.description, ''::text),
    NULLIF(r.user_story, ''::text),
    ('Tags: '::text || COALESCE(string_agg(t.name::text, ', '::text), 'none'::text)),
    ('AC: '::text || COALESCE((SELECT count(*)::text FROM acceptance_criteria ac WHERE ac.requirement_id = r.id), '0'::text)),
    ('BR: '::text || COALESCE((SELECT count(*)::text FROM business_rules br WHERE br.requirement_id = r.id), '0'::text)),
    ('WS: '::text || COALESCE((SELECT count(*)::text FROM workflow_steps ws WHERE ws.requirement_id = r.id), '0'::text))
  ) AS full_context_text,
  COALESCE((SELECT count(*) FROM acceptance_criteria ac WHERE ac.requirement_id = r.id), 0::bigint) AS criteria_count,
  COALESCE((SELECT count(*) FROM business_rules br WHERE br.requirement_id = r.id), 0::bigint) AS rules_count,
  COALESCE((SELECT count(*) FROM workflow_steps ws WHERE ws.requirement_id = r.id), 0::bigint) AS steps_count,
  ARRAY[]::uuid[] AS criteria_ids,
  ARRAY[]::integer[] AS workflow_steps
FROM requirements r
LEFT JOIN requirement_categories rc ON r.category_id = rc.id
LEFT JOIN priority_levels pl ON r.priority_id = pl.id
LEFT JOIN requirement_tags rt ON r.id = rt.requirement_id
LEFT JOIN tags t ON rt.tag_id = t.id
WHERE r.status::text IS DISTINCT FROM 'deprecated'::text
GROUP BY r.id, rc.name, pl.name, pl.level;


-- ============================================================================
-- INDEXES
-- ============================================================================

-- Acceptance Criteria
CREATE INDEX idx_acceptance_criteria_requirement ON public.acceptance_criteria USING btree (requirement_id);

-- AI Insights
CREATE INDEX idx_ai_insights_evidence ON public.ai_insights USING gin (supporting_evidence);

-- AI Interactions
CREATE INDEX ai_interactions_created_at_idx ON public.ai_interactions USING btree (created_at);
CREATE INDEX ai_interactions_project_id_idx ON public.ai_interactions USING btree (project_id);
CREATE INDEX ai_interactions_requirement_id_idx ON public.ai_interactions USING btree (requirement_id);
CREATE INDEX idx_ai_interactions_project ON public.ai_interactions USING btree (project_id, created_at DESC);

-- Business Rules
CREATE INDEX idx_business_rules_requirement ON public.business_rules USING btree (requirement_id);

-- Content Embeddings
CREATE INDEX content_embeddings_content_lookup_idx ON public.content_embeddings USING btree (content_type, content_id);
CREATE INDEX content_embeddings_project_user_idx ON public.content_embeddings USING btree (project_id);
CREATE INDEX idx_content_embeddings_metadata ON public.content_embeddings USING gin (metadata);
CREATE INDEX idx_content_embeddings_project_type ON public.content_embeddings USING btree (project_id, content_type);
CREATE INDEX idx_content_embeddings_vector ON public.content_embeddings USING ivfflat (embedding vector_cosine_ops) WITH (lists='100');

-- Device Tokens
CREATE INDEX device_tokens_user_id_idx ON public.device_tokens USING btree (user_id);

-- Projects
CREATE INDEX idx_projects_keywords ON public.projects USING gin (keywords);

-- Requirement Relationships
CREATE INDEX idx_requirement_relationships_source ON public.requirement_relationships USING btree (source_requirement_id);

-- Requirements
CREATE INDEX idx_active_requirements ON public.requirements USING btree (project_id, status) WHERE status::text <> 'deprecated'::text;
CREATE INDEX idx_requirements_concepts ON public.requirements USING gin (related_concepts);
CREATE INDEX idx_requirements_project_category ON public.requirements USING btree (project_id, category_id);
CREATE INDEX idx_requirements_project_priority ON public.requirements USING btree (project_id, priority_id);

-- Workflow Steps
CREATE INDEX idx_workflow_steps_requirement ON public.workflow_steps USING btree (requirement_id);

-- Blog Authors
CREATE INDEX idx_sws2026_blog_authors_slug ON public.sws2026_blog_authors USING btree (slug);

-- Blog Categories
CREATE INDEX idx_sws2026_blog_categories_display_order ON public.sws2026_blog_categories USING btree (display_order);
CREATE INDEX idx_sws2026_blog_categories_slug ON public.sws2026_blog_categories USING btree (slug);

-- Blog FAQs
CREATE INDEX idx_sws2026_blog_faqs_post ON public.sws2026_blog_faqs USING btree (post_id);

-- Blog Post Embeddings
CREATE INDEX blog_post_embeddings_idx ON public.sws2026_blog_post_embeddings USING hnsw (embedding vector_cosine_ops);

-- Blog Post Tags
CREATE INDEX idx_sws2026_blog_post_tags_post ON public.sws2026_blog_post_tags USING btree (post_id);
CREATE INDEX idx_sws2026_blog_post_tags_tag ON public.sws2026_blog_post_tags USING btree (tag_id);

-- Blog Posts
CREATE INDEX idx_posts_is_lead_article ON public.sws2026_blog_posts USING btree (is_lead_article);
CREATE INDEX idx_posts_survey_id ON public.sws2026_blog_posts USING btree (survey_id);
CREATE INDEX idx_sws2026_blog_posts_author ON public.sws2026_blog_posts USING btree (author_id);
CREATE INDEX idx_sws2026_blog_posts_category ON public.sws2026_blog_posts USING btree (category_id);
CREATE INDEX idx_sws2026_blog_posts_featured ON public.sws2026_blog_posts USING btree (is_featured, featured_order);
CREATE INDEX idx_sws2026_blog_posts_published_at ON public.sws2026_blog_posts USING btree (published_at DESC);
CREATE INDEX idx_sws2026_blog_posts_slug ON public.sws2026_blog_posts USING btree (slug);
CREATE INDEX idx_sws2026_blog_posts_status ON public.sws2026_blog_posts USING btree (status);

-- Blog Related Posts
CREATE INDEX idx_sws2026_blog_related_posts_post ON public.sws2026_blog_related_posts USING btree (post_id);
CREATE INDEX idx_sws2026_blog_related_posts_related ON public.sws2026_blog_related_posts USING btree (related_post_id);

-- Blog Tags
CREATE INDEX idx_sws2026_blog_tags_slug ON public.sws2026_blog_tags USING btree (slug);

-- Blog Writer Sessions
CREATE INDEX idx_blog_writer_sessions_author_id ON public.sws2026_blog_writer_sessions USING btree (author_id);
CREATE INDEX idx_blog_writer_sessions_status ON public.sws2026_blog_writer_sessions USING btree (status);

-- Calendly Bookings
CREATE INDEX idx_calendly_bookings_email ON public.sws2026_calendly_bookings USING btree (invitee_email);
CREATE INDEX idx_calendly_bookings_post_id ON public.sws2026_calendly_bookings USING btree (post_id);
CREATE INDEX idx_calendly_bookings_status ON public.sws2026_calendly_bookings USING btree (status);

-- Chat Conversations
CREATE INDEX idx_chat_conversations_last_message_at ON public.sws2026_chat_conversations USING btree (last_message_at DESC);
CREATE INDEX idx_chat_conversations_status ON public.sws2026_chat_conversations USING btree (status);
CREATE INDEX idx_chat_conversations_visitor_id ON public.sws2026_chat_conversations USING btree (visitor_id);

-- Chat Messages
CREATE INDEX idx_chat_messages_conversation_id ON public.sws2026_chat_messages USING btree (conversation_id);
CREATE INDEX idx_chat_messages_created_at ON public.sws2026_chat_messages USING btree (created_at);

-- Contact Submissions
CREATE INDEX idx_sws2026_contact_submissions_created ON public.sws2026_contact_submissions USING btree (created_at DESC);

-- Enquiries
CREATE INDEX idx_enquiries_created_at ON public.sws2026_enquiries USING btree (created_at DESC);
CREATE INDEX idx_enquiries_post_id ON public.sws2026_enquiries USING btree (post_id);
CREATE INDEX idx_enquiries_status ON public.sws2026_enquiries USING btree (status);
CREATE INDEX idx_enquiries_survey_id ON public.sws2026_enquiries USING btree (survey_id);

-- Help Options
CREATE INDEX idx_help_options_display_order ON public.sws2026_help_options USING btree (display_order, is_active);
CREATE INDEX idx_help_options_post_id ON public.sws2026_help_options USING btree (post_id);

-- Media
CREATE INDEX idx_sws2026_media_created_at ON public.sws2026_media USING btree (created_at DESC);
CREATE INDEX idx_sws2026_media_file_type ON public.sws2026_media USING btree (file_type);
CREATE INDEX idx_sws2026_media_tags ON public.sws2026_media USING gin (tags);

-- Newsletter Subscribers
CREATE INDEX idx_sws2026_newsletter_subscribers_email ON public.sws2026_newsletter_subscribers USING btree (email);

-- Surveys
CREATE INDEX idx_surveys_slug ON public.sws2026_surveys USING btree (slug);
CREATE INDEX idx_surveys_status ON public.sws2026_surveys USING btree (status);


-- ============================================================================
-- FUNCTIONS
-- ============================================================================

-- Update timestamp function
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

-- Handle new user registration (creates profile)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  INSERT INTO public.profiles(id, first_name, last_name, account_code)
  VALUES(
    new.id,
    new.raw_user_meta_data ->> 'first_name',
    new.raw_user_meta_data ->> 'last_name',
    new.raw_user_meta_data ->> 'account_code'
  );
  RETURN new;
END;
$$;

-- Create cost calculator entry
CREATE OR REPLACE FUNCTION public.create_cost_calculator(
  p_first_name text,
  p_last_name text,
  p_phone text,
  p_email text
)
RETURNS TABLE(
  new_id bigint,
  new_first_name text,
  new_last_name text,
  new_phone text,
  new_email text,
  new_uid uuid,
  new_status text,
  new_created_at timestamp with time zone
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    INSERT INTO cost_calculator (first_name, last_name, phone, email, status)
    VALUES (p_first_name, p_last_name, p_phone, p_email, 'new')
    RETURNING id, first_name, last_name, phone, email, uid, status, created_at;
END;
$$;

-- Set service type for cost calculator
CREATE OR REPLACE FUNCTION public.set_service_type(p_uid uuid, p_service_type text)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE cost_calculator SET service_type = p_service_type WHERE uid = p_uid;
END;
$$;

-- Set web application description
CREATE OR REPLACE FUNCTION public.set_web_application(p_uid uuid, p_description text)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE cost_calculator SET app_description = p_description WHERE uid = p_uid;
END;
$$;

-- Get messages with pagination
CREATE OR REPLACE FUNCTION public.get_messages_page(page_index integer, page_size integer)
RETURNS TABLE(
  message_id uuid,
  message_content text,
  message_viewed_at timestamp with time zone,
  message_created_at timestamp with time zone,
  created_by_uuid uuid,
  created_by_first_name text,
  created_by_last_name text,
  created_by_profile_url text,
  topic_id bigint,
  topic_title text,
  topic_summary text,
  topic_logo_url text
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        m.id AS message_id,
        m.content AS message_content,
        m.viewed_at AS message_viewed_at,
        m.created_at AS message_created_at,
        m.created_by AS created_by_uuid,
        p.first_name AS created_by_first_name,
        p.last_name AS created_by_last_name,
        p.profile_url AS created_by_profile_url,
        m.topic_id AS topic_id,
        t.title AS topic_title,
        t.summary AS topic_summary,
        t.logo_url AS topic_logo_url
    FROM
        public.message m
        JOIN public.profiles p ON m.created_by = p.id
        JOIN public.topic t ON m.topic_id = t.id
    ORDER BY
        m.created_at DESC
    OFFSET page_index * page_size
    LIMIT page_size;
END;
$$;

-- Get replies with pagination
CREATE OR REPLACE FUNCTION public.get_replys_page(
  p_message_id uuid,
  page_index integer,
  page_size integer
)
RETURNS TABLE(
  reply_id bigint,
  reply_content text,
  reply_created_at timestamp with time zone,
  reply_creator_id uuid,
  first_name text,
  last_name text,
  profile_url text
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        r.reply_id,
        r.reply_content,
        r.reply_created_at,
        r.reply_creator_id,
        r.first_name,
        r.last_name,
        r.profile_url
    FROM
        public.vw_replies r
    WHERE
        r.message_id = p_message_id
    ORDER BY
        reply_created_at DESC
    OFFSET page_index * page_size
    LIMIT page_size;
END;
$$;

-- Get requirement AI context
CREATE OR REPLACE FUNCTION public.get_requirement_ai_context(project_id_param uuid)
RETURNS TABLE(
  id uuid,
  project_id uuid,
  requirement_id text,
  title text,
  description text,
  user_story text,
  category_name text,
  priority_name text,
  priority_level integer,
  full_context_text text,
  criteria_count bigint,
  rules_count bigint,
  steps_count bigint,
  criteria_ids uuid[],
  workflow_steps integer[]
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    rac.id,
    rac.project_id,
    rac.requirement_id,
    rac.title,
    rac.description,
    rac.user_story,
    rac.category_name,
    rac.priority_name,
    rac.priority_level,
    rac.full_context_text,
    rac.criteria_count,
    rac.rules_count,
    rac.steps_count,
    rac.criteria_ids,
    rac.workflow_steps
  FROM requirement_ai_context rac
  WHERE rac.project_id = project_id_param;
END;
$$;

-- Match content embeddings (semantic search)
CREATE OR REPLACE FUNCTION public.match_content_embeddings(
  query_embedding vector,
  match_project_id uuid,
  match_content_type text,
  match_threshold double precision DEFAULT 0.7,
  match_count integer DEFAULT 10
)
RETURNS TABLE(
  content_id uuid,
  content_type character varying,
  content_text text,
  similarity double precision,
  metadata jsonb
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    ce.content_id,
    ce.content_type,
    ce.content_text,
    (1 - (ce.embedding <=> query_embedding)) AS similarity,
    ce.metadata
  FROM content_embeddings ce
  WHERE ce.project_id = match_project_id
    AND ce.content_type = match_content_type
    AND (1 - (ce.embedding <=> query_embedding)) > match_threshold
  ORDER BY ce.embedding <=> query_embedding
  LIMIT match_count;
END;
$$;

-- Search blog posts (semantic search)
CREATE OR REPLACE FUNCTION public.search_blog_posts(
  query_embedding vector,
  match_threshold double precision DEFAULT 0.3,
  match_count integer DEFAULT 6
)
RETURNS TABLE(
  id uuid,
  title character varying,
  slug character varying,
  excerpt text,
  featured_image text,
  published_at timestamp with time zone,
  category_name character varying,
  similarity double precision
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    p.id,
    p.title,
    p.slug,
    p.excerpt,
    p.featured_image,
    p.published_at,
    c.name as category_name,
    1 - (e.embedding <=> query_embedding) as similarity
  FROM sws2026_blog_post_embeddings e
  JOIN sws2026_blog_posts p ON p.id = e.post_id
  LEFT JOIN sws2026_blog_categories c ON c.id = p.category_id
  WHERE p.status = 'published'
    AND e.embedding IS NOT NULL
    AND 1 - (e.embedding <=> query_embedding) > match_threshold
  ORDER BY e.embedding <=> query_embedding
  LIMIT match_count;
END;
$$;

-- Set live chat status
CREATE OR REPLACE FUNCTION public.set_live_chat_status(status boolean)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
  UPDATE sws2026_live_chat_settings
  SET is_online = status, updated_at = NOW();
END;
$$;

-- Update blog writer sessions timestamp
CREATE OR REPLACE FUNCTION public.update_blog_writer_sessions_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

-- Refresh requirement context (materialized view)
CREATE OR REPLACE FUNCTION public.refresh_requirement_context()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  REFRESH MATERIALIZED VIEW CONCURRENTLY requirement_ai_context;
  RETURN NULL;
END;
$$;


-- ============================================================================
-- TRIGGERS
-- ============================================================================

-- Update timestamps
CREATE TRIGGER update_content_embeddings_updated_at
  BEFORE UPDATE ON public.content_embeddings
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_projects_updated_at
  BEFORE UPDATE ON public.projects
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_requirements_updated_at
  BEFORE UPDATE ON public.requirements
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER blog_writer_sessions_updated_at
  BEFORE UPDATE ON public.sws2026_blog_writer_sessions
  FOR EACH ROW EXECUTE FUNCTION update_blog_writer_sessions_updated_at();

-- Push notification trigger
CREATE TRIGGER push
  AFTER INSERT ON public.notifications
  FOR EACH ROW
  EXECUTE FUNCTION supabase_functions.http_request(
    'https://dbdnibcfezptsdzymafb.supabase.co/functions/v1/push',
    'POST',
    '{"Content-type":"application/json"}',
    '{}',
    '1000'
  );


-- ============================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ============================================================================

-- Enable RLS on all tables
ALTER TABLE public.acceptance_criteria ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_insights ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_interactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.business_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categorys ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.content_block ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.content_embeddings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cost_calculator ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customer ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.data_requirements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.device_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.integration_requirements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.message ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_glossary ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_user_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reply ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.requirement_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.requirement_changes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.requirement_relationships ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.requirement_risks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.requirement_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.requirements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scratch ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sws2026_blocked_ips ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sws2026_blog_authors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sws2026_blog_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sws2026_blog_faqs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sws2026_blog_post_embeddings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sws2026_blog_post_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sws2026_blog_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sws2026_blog_related_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sws2026_blog_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sws2026_blog_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sws2026_blog_writer_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sws2026_calendly_bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sws2026_chat_conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sws2026_chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sws2026_contact_submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sws2026_enquiries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sws2026_help_options ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sws2026_live_chat_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sws2026_media ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sws2026_newsletter_subscribers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sws2026_surveys ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.topic ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workflow_steps ENABLE ROW LEVEL SECURITY;

-- Note: notifications and priority_levels have RLS disabled

-- ----------------------------------------------------------------------------
-- Profiles Policies
-- ----------------------------------------------------------------------------
CREATE POLICY "Users can view own profile" ON public.profiles
  FOR SELECT TO authenticated USING (auth.uid() = id);

CREATE POLICY "Users can update own profile" ON public.profiles
  FOR UPDATE TO authenticated USING (auth.uid() = id);

-- ----------------------------------------------------------------------------
-- Message Policies
-- ----------------------------------------------------------------------------
CREATE POLICY "Users can view own messages." ON public.message
  FOR SELECT TO public USING (true);

CREATE POLICY "Users can add messages" ON public.message
  FOR INSERT TO authenticated WITH CHECK (auth.uid() = created_by);

CREATE POLICY "Users can update own messages" ON public.message
  FOR UPDATE TO authenticated USING (auth.uid() = created_by);

CREATE POLICY "Users can delete own messages" ON public.message
  FOR DELETE TO authenticated USING (auth.uid() = created_by);

-- ----------------------------------------------------------------------------
-- Reply Policies
-- ----------------------------------------------------------------------------
CREATE POLICY "Users can see their own replies" ON public.reply
  FOR SELECT TO authenticated USING (created_by = auth.uid());

CREATE POLICY "Users can insert a reply" ON public.reply
  FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Users can update their own replies" ON public.reply
  FOR UPDATE TO authenticated USING (created_by = auth.uid());

CREATE POLICY "Users can delete their own replies." ON public.reply
  FOR DELETE TO authenticated USING (created_by = auth.uid());

-- ----------------------------------------------------------------------------
-- Topic Policies
-- ----------------------------------------------------------------------------
CREATE POLICY "Authenticated can view topics" ON public.topic
  FOR SELECT TO authenticated USING (true);

-- ----------------------------------------------------------------------------
-- Device Tokens Policies
-- ----------------------------------------------------------------------------
CREATE POLICY "Users can view their own device tokens" ON public.device_tokens
  FOR SELECT TO public USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own device tokens" ON public.device_tokens
  FOR INSERT TO public WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own device tokens" ON public.device_tokens
  FOR UPDATE TO public USING (auth.uid() = user_id);

-- ----------------------------------------------------------------------------
-- Articles & Content Policies
-- ----------------------------------------------------------------------------
CREATE POLICY "Enable read access for all users" ON public.articles
  FOR SELECT TO public USING (true);

CREATE POLICY "Enable read access for all users" ON public.categorys
  FOR SELECT TO public USING (true);

CREATE POLICY "Enable read access for all users" ON public.content_block
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "Enable read access for all users" ON public.services
  FOR SELECT TO authenticated USING (true);

-- ----------------------------------------------------------------------------
-- Customer Policies
-- ----------------------------------------------------------------------------
CREATE POLICY "Keep select private" ON public.customer
  FOR SELECT TO authenticated USING (false);

-- ----------------------------------------------------------------------------
-- Projects Policies
-- ----------------------------------------------------------------------------
CREATE POLICY "users_own_projects" ON public.projects
  FOR ALL TO public USING (auth.uid() = user_id);

-- ----------------------------------------------------------------------------
-- Requirements Policies
-- ----------------------------------------------------------------------------
CREATE POLICY "users_project_requirements" ON public.requirements
  FOR ALL TO public
  USING (EXISTS (SELECT 1 FROM projects WHERE projects.id = requirements.project_id AND projects.user_id = auth.uid()));

CREATE POLICY "Authenticated users can access all requirements" ON public.requirements
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- ----------------------------------------------------------------------------
-- Acceptance Criteria Policies
-- ----------------------------------------------------------------------------
CREATE POLICY "users_acceptance_criteria" ON public.acceptance_criteria
  FOR ALL TO public
  USING (EXISTS (
    SELECT 1 FROM requirements r
    JOIN projects p ON p.id = r.project_id
    WHERE r.id = acceptance_criteria.requirement_id AND p.user_id = auth.uid()
  ));

-- ----------------------------------------------------------------------------
-- Tags Policies
-- ----------------------------------------------------------------------------
CREATE POLICY "Allow select for project members" ON public.tags
  FOR SELECT TO public
  USING (EXISTS (SELECT 1 FROM projects p WHERE p.id = tags.project_id AND p.user_id = auth.uid()));

CREATE POLICY "Allow insert for project members" ON public.tags
  FOR INSERT TO public
  WITH CHECK (EXISTS (SELECT 1 FROM projects p WHERE p.id = tags.project_id AND p.user_id = auth.uid()));

CREATE POLICY "Allow update for project members" ON public.tags
  FOR UPDATE TO public
  USING (EXISTS (SELECT 1 FROM projects p WHERE p.id = tags.project_id AND p.user_id = auth.uid()));

CREATE POLICY "Allow delete for project members" ON public.tags
  FOR DELETE TO public
  USING (EXISTS (SELECT 1 FROM projects p WHERE p.id = tags.project_id AND p.user_id = auth.uid()));

-- ----------------------------------------------------------------------------
-- Requirement Tags Policies
-- ----------------------------------------------------------------------------
CREATE POLICY "Allow select for project members" ON public.requirement_tags
  FOR SELECT TO public
  USING (EXISTS (
    SELECT 1 FROM requirements r
    JOIN projects p ON r.project_id = p.id
    WHERE r.id = requirement_tags.requirement_id AND p.user_id = auth.uid()
  ));

CREATE POLICY "Allow insert for project members" ON public.requirement_tags
  FOR INSERT TO public
  WITH CHECK (EXISTS (
    SELECT 1 FROM requirements r
    JOIN projects p ON r.project_id = p.id
    WHERE r.id = requirement_tags.requirement_id AND p.user_id = auth.uid()
  ));

CREATE POLICY "Allow delete for project members" ON public.requirement_tags
  FOR DELETE TO public
  USING (EXISTS (
    SELECT 1 FROM requirements r
    JOIN projects p ON r.project_id = p.id
    WHERE r.id = requirement_tags.requirement_id AND p.user_id = auth.uid()
  ));

-- ----------------------------------------------------------------------------
-- Content Embeddings Policies
-- ----------------------------------------------------------------------------
CREATE POLICY "Users can access embeddings from their projects" ON public.content_embeddings
  FOR ALL TO authenticated
  USING (project_id IN (SELECT id FROM projects WHERE user_id = auth.uid()))
  WITH CHECK (project_id IN (SELECT id FROM projects WHERE user_id = auth.uid()));

CREATE POLICY "users_project_embeddings" ON public.content_embeddings
  FOR ALL TO public
  USING (EXISTS (SELECT 1 FROM projects WHERE projects.id = content_embeddings.project_id AND projects.user_id = auth.uid()));

-- ----------------------------------------------------------------------------
-- AI Interactions Policies
-- ----------------------------------------------------------------------------
CREATE POLICY "Users can access interactions from their projects" ON public.ai_interactions
  FOR ALL TO authenticated
  USING (project_id IN (SELECT id FROM projects WHERE user_id = auth.uid()))
  WITH CHECK (project_id IN (SELECT id FROM projects WHERE user_id = auth.uid()));

-- ----------------------------------------------------------------------------
-- Blog Authors Policies
-- ----------------------------------------------------------------------------
CREATE POLICY "Public can view active authors" ON public.sws2026_blog_authors
  FOR SELECT TO public USING (is_active = true);

CREATE POLICY "Authenticated users can view authors" ON public.sws2026_blog_authors
  FOR SELECT TO authenticated USING (true);

-- ----------------------------------------------------------------------------
-- Blog Categories Policies
-- ----------------------------------------------------------------------------
CREATE POLICY "Public can view categories" ON public.sws2026_blog_categories
  FOR SELECT TO public USING (true);

CREATE POLICY "Authors can insert categories" ON public.sws2026_blog_categories
  FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM sws2026_blog_authors WHERE user_id = auth.uid() AND is_active = true));

CREATE POLICY "Authors can update categories" ON public.sws2026_blog_categories
  FOR UPDATE TO authenticated
  USING (EXISTS (SELECT 1 FROM sws2026_blog_authors WHERE user_id = auth.uid() AND is_active = true));

CREATE POLICY "Authors can delete categories" ON public.sws2026_blog_categories
  FOR DELETE TO authenticated
  USING (EXISTS (SELECT 1 FROM sws2026_blog_authors WHERE user_id = auth.uid() AND is_active = true));

-- ----------------------------------------------------------------------------
-- Blog Tags Policies
-- ----------------------------------------------------------------------------
CREATE POLICY "Public can view tags" ON public.sws2026_blog_tags
  FOR SELECT TO public USING (true);

CREATE POLICY "Authors can insert tags" ON public.sws2026_blog_tags
  FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM sws2026_blog_authors WHERE user_id = auth.uid() AND is_active = true));

CREATE POLICY "Authors can update tags" ON public.sws2026_blog_tags
  FOR UPDATE TO authenticated
  USING (EXISTS (SELECT 1 FROM sws2026_blog_authors WHERE user_id = auth.uid() AND is_active = true));

CREATE POLICY "Authors can delete tags" ON public.sws2026_blog_tags
  FOR DELETE TO authenticated
  USING (EXISTS (SELECT 1 FROM sws2026_blog_authors WHERE user_id = auth.uid() AND is_active = true));

-- ----------------------------------------------------------------------------
-- Blog Posts Policies
-- ----------------------------------------------------------------------------
CREATE POLICY "Public can view published posts" ON public.sws2026_blog_posts
  FOR SELECT TO public USING (status = 'published' AND published_at <= now());

CREATE POLICY "Authors can view their own posts" ON public.sws2026_blog_posts
  FOR SELECT TO authenticated
  USING (author_id IN (SELECT id FROM sws2026_blog_authors WHERE user_id = auth.uid()));

CREATE POLICY "Authors can insert posts" ON public.sws2026_blog_posts
  FOR INSERT TO authenticated
  WITH CHECK (author_id IN (SELECT id FROM sws2026_blog_authors WHERE user_id = auth.uid()));

CREATE POLICY "Authors can update their posts" ON public.sws2026_blog_posts
  FOR UPDATE TO authenticated
  USING (author_id IN (SELECT id FROM sws2026_blog_authors WHERE user_id = auth.uid()))
  WITH CHECK (author_id IN (SELECT id FROM sws2026_blog_authors WHERE user_id = auth.uid()));

CREATE POLICY "Authors can delete their posts" ON public.sws2026_blog_posts
  FOR DELETE TO authenticated
  USING (author_id IN (SELECT id FROM sws2026_blog_authors WHERE user_id = auth.uid()));

-- ----------------------------------------------------------------------------
-- Blog Post Tags Policies
-- ----------------------------------------------------------------------------
CREATE POLICY "Public can view post tags" ON public.sws2026_blog_post_tags
  FOR SELECT TO public USING (true);

CREATE POLICY "Authors can insert post tags" ON public.sws2026_blog_post_tags
  FOR INSERT TO authenticated
  WITH CHECK (post_id IN (
    SELECT id FROM sws2026_blog_posts WHERE author_id IN (
      SELECT id FROM sws2026_blog_authors WHERE user_id = auth.uid()
    )
  ));

CREATE POLICY "Authors can delete post tags" ON public.sws2026_blog_post_tags
  FOR DELETE TO authenticated
  USING (post_id IN (
    SELECT id FROM sws2026_blog_posts WHERE author_id IN (
      SELECT id FROM sws2026_blog_authors WHERE user_id = auth.uid()
    )
  ));

-- ----------------------------------------------------------------------------
-- Blog FAQs Policies
-- ----------------------------------------------------------------------------
CREATE POLICY "Public can view post FAQs" ON public.sws2026_blog_faqs
  FOR SELECT TO public USING (true);

CREATE POLICY "Authors can insert FAQs" ON public.sws2026_blog_faqs
  FOR INSERT TO authenticated
  WITH CHECK (post_id IN (
    SELECT id FROM sws2026_blog_posts WHERE author_id IN (
      SELECT id FROM sws2026_blog_authors WHERE user_id = auth.uid()
    )
  ));

CREATE POLICY "Authors can update FAQs" ON public.sws2026_blog_faqs
  FOR UPDATE TO authenticated
  USING (post_id IN (
    SELECT id FROM sws2026_blog_posts WHERE author_id IN (
      SELECT id FROM sws2026_blog_authors WHERE user_id = auth.uid()
    )
  ));

CREATE POLICY "Authors can delete FAQs" ON public.sws2026_blog_faqs
  FOR DELETE TO authenticated
  USING (post_id IN (
    SELECT id FROM sws2026_blog_posts WHERE author_id IN (
      SELECT id FROM sws2026_blog_authors WHERE user_id = auth.uid()
    )
  ));

-- ----------------------------------------------------------------------------
-- Blog Related Posts Policies
-- ----------------------------------------------------------------------------
CREATE POLICY "Public can view related posts" ON public.sws2026_blog_related_posts
  FOR SELECT TO public USING (true);

-- ----------------------------------------------------------------------------
-- Blog Settings Policies
-- ----------------------------------------------------------------------------
CREATE POLICY "Public can view settings" ON public.sws2026_blog_settings
  FOR SELECT TO public USING (true);

-- ----------------------------------------------------------------------------
-- Blog Post Embeddings Policies
-- ----------------------------------------------------------------------------
CREATE POLICY "Public can read embeddings" ON public.sws2026_blog_post_embeddings
  FOR SELECT TO public USING (true);

CREATE POLICY "Authenticated users can manage embeddings" ON public.sws2026_blog_post_embeddings
  FOR ALL TO public USING (auth.role() = 'authenticated');

-- ----------------------------------------------------------------------------
-- Blog Writer Sessions Policies
-- ----------------------------------------------------------------------------
CREATE POLICY "Authors can view own sessions" ON public.sws2026_blog_writer_sessions
  FOR SELECT TO public
  USING (author_id IN (SELECT id FROM sws2026_blog_authors WHERE user_id = auth.uid()));

CREATE POLICY "Authors can insert own sessions" ON public.sws2026_blog_writer_sessions
  FOR INSERT TO public
  WITH CHECK (author_id IN (SELECT id FROM sws2026_blog_authors WHERE user_id = auth.uid()));

CREATE POLICY "Authors can update own sessions" ON public.sws2026_blog_writer_sessions
  FOR UPDATE TO public
  USING (author_id IN (SELECT id FROM sws2026_blog_authors WHERE user_id = auth.uid()));

CREATE POLICY "Authors can delete own sessions" ON public.sws2026_blog_writer_sessions
  FOR DELETE TO public
  USING (author_id IN (SELECT id FROM sws2026_blog_authors WHERE user_id = auth.uid()));

-- ----------------------------------------------------------------------------
-- Surveys Policies
-- ----------------------------------------------------------------------------
CREATE POLICY "Allow public read for active surveys" ON public.sws2026_surveys
  FOR SELECT TO public USING (status = 'active');

CREATE POLICY "Allow authenticated users full access to surveys" ON public.sws2026_surveys
  FOR ALL TO public USING (auth.role() = 'authenticated');

-- ----------------------------------------------------------------------------
-- Enquiries Policies
-- ----------------------------------------------------------------------------
CREATE POLICY "Allow public insert for enquiries" ON public.sws2026_enquiries
  FOR INSERT TO public WITH CHECK (true);

CREATE POLICY "Allow authenticated users full access to enquiries" ON public.sws2026_enquiries
  FOR ALL TO public USING (auth.role() = 'authenticated');

-- ----------------------------------------------------------------------------
-- Calendly Bookings Policies
-- ----------------------------------------------------------------------------
CREATE POLICY "Allow anonymous to insert bookings" ON public.sws2026_calendly_bookings
  FOR INSERT TO anon WITH CHECK (true);

CREATE POLICY "Allow authenticated full access to bookings" ON public.sws2026_calendly_bookings
  FOR ALL TO authenticated USING (true);

-- ----------------------------------------------------------------------------
-- Live Chat Settings Policies
-- ----------------------------------------------------------------------------
CREATE POLICY "Anyone can read chat settings" ON public.sws2026_live_chat_settings
  FOR SELECT TO public USING (true);

CREATE POLICY "Authenticated users can insert chat settings" ON public.sws2026_live_chat_settings
  FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Authenticated users can update chat settings" ON public.sws2026_live_chat_settings
  FOR UPDATE TO authenticated USING (true);

-- ----------------------------------------------------------------------------
-- Chat Conversations Policies
-- ----------------------------------------------------------------------------
CREATE POLICY "Authenticated users can read all conversations" ON public.sws2026_chat_conversations
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "Authenticated users can update conversations" ON public.sws2026_chat_conversations
  FOR UPDATE TO authenticated USING (true);

CREATE POLICY "Authenticated users can delete conversations" ON public.sws2026_chat_conversations
  FOR DELETE TO authenticated USING (true);

-- ----------------------------------------------------------------------------
-- Chat Messages Policies
-- ----------------------------------------------------------------------------
CREATE POLICY "Authenticated users can read all messages" ON public.sws2026_chat_messages
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "Authenticated users can create messages" ON public.sws2026_chat_messages
  FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Authenticated users can update messages" ON public.sws2026_chat_messages
  FOR UPDATE TO authenticated USING (true);

CREATE POLICY "Authenticated users can delete messages" ON public.sws2026_chat_messages
  FOR DELETE TO authenticated USING (true);

CREATE POLICY "Public can create visitor messages" ON public.sws2026_chat_messages
  FOR INSERT TO public WITH CHECK (sender_type = 'visitor');

-- ----------------------------------------------------------------------------
-- Blocked IPs Policies
-- ----------------------------------------------------------------------------
CREATE POLICY "Anyone can read blocked IPs" ON public.sws2026_blocked_ips
  FOR SELECT TO public USING (true);

CREATE POLICY "Admin can manage blocked IPs" ON public.sws2026_blocked_ips
  FOR ALL TO authenticated USING (true);

-- ----------------------------------------------------------------------------
-- Contact Submissions Policies
-- ----------------------------------------------------------------------------
CREATE POLICY "Anyone can submit contact" ON public.sws2026_contact_submissions
  FOR INSERT TO public WITH CHECK (true);

-- ----------------------------------------------------------------------------
-- Newsletter Subscribers Policies
-- ----------------------------------------------------------------------------
CREATE POLICY "Anyone can subscribe" ON public.sws2026_newsletter_subscribers
  FOR INSERT TO public WITH CHECK (true);

-- ----------------------------------------------------------------------------
-- Media Policies
-- ----------------------------------------------------------------------------
CREATE POLICY "Public can view media" ON public.sws2026_media
  FOR SELECT TO public USING (true);

CREATE POLICY "Authenticated users can upload media" ON public.sws2026_media
  FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Authenticated users can update media" ON public.sws2026_media
  FOR UPDATE TO authenticated USING (true);

CREATE POLICY "Authenticated users can delete media" ON public.sws2026_media
  FOR DELETE TO authenticated USING (true);

-- ----------------------------------------------------------------------------
-- Help Options Policies
-- ----------------------------------------------------------------------------
CREATE POLICY "Public can view active help options" ON public.sws2026_help_options
  FOR SELECT TO public USING (is_active = true);

CREATE POLICY "Admin can manage help options" ON public.sws2026_help_options
  FOR ALL TO public USING (true) WITH CHECK (true);


-- ============================================================================
-- EDGE FUNCTIONS (Supabase Functions)
-- ============================================================================
-- Note: Edge functions are deployed separately via Supabase CLI
-- The following edge functions are deployed:
--
-- 1. getMessagePage (JWT required)
--    - Retrieves paginated messages
--
-- 2. getMessage (JWT required)
--    - Gets a single message
--
-- 3. getReplyPage (JWT required)
--    - Retrieves paginated replies
--
-- 4. newCustomer (No JWT - public)
--    - Creates new customer records
--
-- 5. push (No JWT - webhook)
--    - Handles push notification delivery
--
-- 6. sendNotification (JWT required)
--    - Sends notifications to users
--
-- 7. ai-requirements-assistant (JWT required)
--    - AI-powered requirements analysis
--
-- 8. generate-embedding (JWT required)
--    - Generates vector embeddings for content
--
-- 9. ai-analyze-requirement-atomicity (JWT required)
--    - Analyzes if requirements are atomic
--
-- 10. ai-split-requirement (JWT required)
--     - Splits complex requirements into atomic ones
