-- ============================================================================
-- SUPABASE AUTH SCHEMA DUMP
-- Generated: 2026-01-18
-- ============================================================================
--
-- IMPORTANT NOTE:
-- The auth schema is managed by Supabase and should NOT be modified directly.
-- This file is for documentation and reference purposes only.
--
-- To make changes to auth behavior, use:
-- 1. Supabase Dashboard Auth Settings
-- 2. Custom triggers on auth.users (like handle_new_user)
-- 3. Edge Functions for custom auth flows
-- ============================================================================


-- ============================================================================
-- TABLES
-- ============================================================================

-- ----------------------------------------------------------------------------
-- auth.users - Core user accounts table
-- ----------------------------------------------------------------------------
-- This table stores all authenticated users
CREATE TABLE auth.users (
  instance_id uuid,
  id uuid NOT NULL PRIMARY KEY,
  aud character varying(255),
  role character varying(255),
  email character varying(255),
  encrypted_password character varying(255),
  email_confirmed_at timestamp with time zone,
  invited_at timestamp with time zone,
  confirmation_token character varying(255),
  confirmation_sent_at timestamp with time zone,
  recovery_token character varying(255),
  recovery_sent_at timestamp with time zone,
  email_change_token_new character varying(255),
  email_change character varying(255),
  email_change_sent_at timestamp with time zone,
  last_sign_in_at timestamp with time zone,
  raw_app_meta_data jsonb,
  raw_user_meta_data jsonb,
  is_super_admin boolean,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  phone text DEFAULT NULL,
  phone_confirmed_at timestamp with time zone,
  phone_change text DEFAULT '',
  phone_change_token character varying(255) DEFAULT '',
  phone_change_sent_at timestamp with time zone,
  confirmed_at timestamp with time zone,
  email_change_token_current character varying(255) DEFAULT '',
  email_change_confirm_status smallint DEFAULT 0,
  banned_until timestamp with time zone,
  reauthentication_token character varying(255) DEFAULT '',
  reauthentication_sent_at timestamp with time zone,
  is_sso_user boolean NOT NULL DEFAULT false,
  deleted_at timestamp with time zone,
  is_anonymous boolean NOT NULL DEFAULT false
);

-- ----------------------------------------------------------------------------
-- auth.identities - User identity providers
-- ----------------------------------------------------------------------------
-- Links users to their authentication providers (email, Google, GitHub, etc.)
CREATE TABLE auth.identities (
  provider_id text NOT NULL,
  user_id uuid NOT NULL,
  identity_data jsonb NOT NULL,
  provider text NOT NULL,
  last_sign_in_at timestamp with time zone,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  email text,
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  CONSTRAINT identities_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE
);

-- ----------------------------------------------------------------------------
-- auth.sessions - Active user sessions
-- ----------------------------------------------------------------------------
CREATE TABLE auth.sessions (
  id uuid NOT NULL PRIMARY KEY,
  user_id uuid NOT NULL,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  factor_id uuid,
  aal auth.aal_level,
  not_after timestamp with time zone,
  refreshed_at timestamp without time zone,
  user_agent text,
  ip inet,
  tag text,
  oauth_client_id uuid,
  refresh_token_hmac_key text,
  refresh_token_counter bigint,
  scopes text,
  CONSTRAINT sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE
);

-- ----------------------------------------------------------------------------
-- auth.refresh_tokens - JWT refresh tokens
-- ----------------------------------------------------------------------------
CREATE TABLE auth.refresh_tokens (
  instance_id uuid,
  id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  token character varying(255),
  user_id character varying(255),
  revoked boolean,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  parent character varying(255),
  session_id uuid,
  CONSTRAINT refresh_tokens_session_id_fkey FOREIGN KEY (session_id) REFERENCES auth.sessions(id) ON DELETE CASCADE
);

-- ----------------------------------------------------------------------------
-- auth.audit_log_entries - Authentication audit log
-- ----------------------------------------------------------------------------
CREATE TABLE auth.audit_log_entries (
  instance_id uuid,
  id uuid NOT NULL PRIMARY KEY,
  payload json,
  created_at timestamp with time zone,
  ip_address character varying(64) NOT NULL DEFAULT ''
);

-- ----------------------------------------------------------------------------
-- auth.instances - Multi-tenant instances
-- ----------------------------------------------------------------------------
CREATE TABLE auth.instances (
  id uuid NOT NULL PRIMARY KEY,
  uuid uuid,
  raw_base_config text,
  created_at timestamp with time zone,
  updated_at timestamp with time zone
);

-- ----------------------------------------------------------------------------
-- auth.schema_migrations - Auth schema version tracking
-- ----------------------------------------------------------------------------
CREATE TABLE auth.schema_migrations (
  version character varying(255) NOT NULL PRIMARY KEY
);


-- ============================================================================
-- MFA (Multi-Factor Authentication) TABLES
-- ============================================================================

-- ----------------------------------------------------------------------------
-- auth.mfa_factors - MFA methods registered by users
-- ----------------------------------------------------------------------------
CREATE TABLE auth.mfa_factors (
  id uuid NOT NULL PRIMARY KEY,
  user_id uuid NOT NULL,
  friendly_name text,
  factor_type auth.factor_type NOT NULL,
  status auth.factor_status NOT NULL,
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL,
  secret text,
  phone text,
  last_challenged_at timestamp with time zone,
  web_authn_credential jsonb,
  web_authn_aaguid uuid,
  last_webauthn_challenge_data jsonb,
  CONSTRAINT mfa_factors_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE
);

-- ----------------------------------------------------------------------------
-- auth.mfa_challenges - MFA challenge/response records
-- ----------------------------------------------------------------------------
CREATE TABLE auth.mfa_challenges (
  id uuid NOT NULL PRIMARY KEY,
  factor_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL,
  verified_at timestamp with time zone,
  ip_address inet NOT NULL,
  otp_code text,
  web_authn_session_data jsonb,
  CONSTRAINT mfa_challenges_factor_id_fkey FOREIGN KEY (factor_id) REFERENCES auth.mfa_factors(id) ON DELETE CASCADE
);

-- ----------------------------------------------------------------------------
-- auth.mfa_amr_claims - Authentication Method Reference claims
-- ----------------------------------------------------------------------------
CREATE TABLE auth.mfa_amr_claims (
  session_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL,
  authentication_method text NOT NULL,
  id uuid NOT NULL PRIMARY KEY,
  CONSTRAINT mfa_amr_claims_session_id_fkey FOREIGN KEY (session_id) REFERENCES auth.sessions(id) ON DELETE CASCADE
);


-- ============================================================================
-- SSO (Single Sign-On) TABLES
-- ============================================================================

-- ----------------------------------------------------------------------------
-- auth.sso_providers - SSO provider configurations
-- ----------------------------------------------------------------------------
CREATE TABLE auth.sso_providers (
  id uuid NOT NULL PRIMARY KEY,
  resource_id text,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  disabled boolean
);

-- ----------------------------------------------------------------------------
-- auth.sso_domains - Email domains linked to SSO providers
-- ----------------------------------------------------------------------------
CREATE TABLE auth.sso_domains (
  id uuid NOT NULL PRIMARY KEY,
  sso_provider_id uuid NOT NULL,
  domain text NOT NULL,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  CONSTRAINT sso_domains_sso_provider_id_fkey FOREIGN KEY (sso_provider_id) REFERENCES auth.sso_providers(id) ON DELETE CASCADE
);

-- ----------------------------------------------------------------------------
-- auth.saml_providers - SAML provider configurations
-- ----------------------------------------------------------------------------
CREATE TABLE auth.saml_providers (
  id uuid NOT NULL PRIMARY KEY,
  sso_provider_id uuid NOT NULL,
  entity_id text NOT NULL,
  metadata_xml text NOT NULL,
  metadata_url text,
  attribute_mapping jsonb,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  name_id_format text,
  CONSTRAINT saml_providers_sso_provider_id_fkey FOREIGN KEY (sso_provider_id) REFERENCES auth.sso_providers(id) ON DELETE CASCADE
);

-- ----------------------------------------------------------------------------
-- auth.saml_relay_states - SAML relay state for SSO flows
-- ----------------------------------------------------------------------------
CREATE TABLE auth.saml_relay_states (
  id uuid NOT NULL PRIMARY KEY,
  sso_provider_id uuid NOT NULL,
  request_id text NOT NULL,
  for_email text,
  redirect_to text,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  flow_state_id uuid,
  CONSTRAINT saml_relay_states_sso_provider_id_fkey FOREIGN KEY (sso_provider_id) REFERENCES auth.sso_providers(id) ON DELETE CASCADE,
  CONSTRAINT saml_relay_states_flow_state_id_fkey FOREIGN KEY (flow_state_id) REFERENCES auth.flow_state(id) ON DELETE CASCADE
);


-- ============================================================================
-- OAUTH TABLES
-- ============================================================================

-- ----------------------------------------------------------------------------
-- auth.oauth_clients - OAuth client applications
-- ----------------------------------------------------------------------------
CREATE TABLE auth.oauth_clients (
  id uuid NOT NULL PRIMARY KEY,
  client_secret_hash text,
  registration_type auth.oauth_registration_type NOT NULL,
  redirect_uris text NOT NULL,
  grant_types text NOT NULL,
  client_name text,
  client_uri text,
  logo_uri text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_at timestamp with time zone,
  client_type auth.oauth_client_type NOT NULL DEFAULT 'confidential'
);

-- ----------------------------------------------------------------------------
-- auth.oauth_authorizations - OAuth authorization grants
-- ----------------------------------------------------------------------------
CREATE TABLE auth.oauth_authorizations (
  id uuid NOT NULL PRIMARY KEY,
  authorization_id text NOT NULL,
  client_id uuid NOT NULL,
  user_id uuid,
  redirect_uri text NOT NULL,
  scope text NOT NULL,
  state text,
  resource text,
  code_challenge text,
  code_challenge_method auth.code_challenge_method,
  response_type auth.oauth_response_type NOT NULL DEFAULT 'code',
  status auth.oauth_authorization_status NOT NULL DEFAULT 'pending',
  authorization_code text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone NOT NULL DEFAULT (now() + '00:03:00'::interval),
  approved_at timestamp with time zone,
  nonce text,
  CONSTRAINT oauth_authorizations_client_id_fkey FOREIGN KEY (client_id) REFERENCES auth.oauth_clients(id) ON DELETE CASCADE,
  CONSTRAINT oauth_authorizations_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE
);

-- ----------------------------------------------------------------------------
-- auth.oauth_consents - User consent records for OAuth apps
-- ----------------------------------------------------------------------------
CREATE TABLE auth.oauth_consents (
  id uuid NOT NULL PRIMARY KEY,
  user_id uuid NOT NULL,
  client_id uuid NOT NULL,
  scopes text NOT NULL,
  granted_at timestamp with time zone NOT NULL DEFAULT now(),
  revoked_at timestamp with time zone,
  CONSTRAINT oauth_consents_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE,
  CONSTRAINT oauth_consents_client_id_fkey FOREIGN KEY (client_id) REFERENCES auth.oauth_clients(id) ON DELETE CASCADE
);

-- ----------------------------------------------------------------------------
-- auth.oauth_client_states - OAuth client state for PKCE flows
-- ----------------------------------------------------------------------------
CREATE TABLE auth.oauth_client_states (
  id uuid NOT NULL PRIMARY KEY,
  provider_type text NOT NULL,
  code_verifier text,
  created_at timestamp with time zone NOT NULL
);


-- ============================================================================
-- FLOW & TOKEN TABLES
-- ============================================================================

-- ----------------------------------------------------------------------------
-- auth.flow_state - PKCE and OAuth flow state
-- ----------------------------------------------------------------------------
CREATE TABLE auth.flow_state (
  id uuid NOT NULL PRIMARY KEY,
  user_id uuid,
  auth_code text NOT NULL,
  code_challenge_method auth.code_challenge_method NOT NULL,
  code_challenge text NOT NULL,
  provider_type text NOT NULL,
  provider_access_token text,
  provider_refresh_token text,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  authentication_method text NOT NULL,
  auth_code_issued_at timestamp with time zone
);

-- ----------------------------------------------------------------------------
-- auth.one_time_tokens - Tokens for email verification, password reset, etc.
-- ----------------------------------------------------------------------------
CREATE TABLE auth.one_time_tokens (
  id uuid NOT NULL PRIMARY KEY,
  user_id uuid NOT NULL,
  token_type auth.one_time_token_type NOT NULL,
  token_hash text NOT NULL,
  relates_to text NOT NULL,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT one_time_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE
);


-- ============================================================================
-- CUSTOM ENUM TYPES (Defined by Supabase Auth)
-- ============================================================================

-- auth.aal_level: 'aal1', 'aal2', 'aal3' (Authentication Assurance Level)
-- auth.factor_type: 'totp', 'webauthn', 'phone'
-- auth.factor_status: 'unverified', 'verified'
-- auth.code_challenge_method: 'plain', 's256'
-- auth.oauth_registration_type: 'static', 'dynamic'
-- auth.oauth_client_type: 'public', 'confidential'
-- auth.oauth_response_type: 'code', 'token'
-- auth.oauth_authorization_status: 'pending', 'approved', 'rejected'
-- auth.one_time_token_type: various token types


-- ============================================================================
-- TRIGGERS
-- ============================================================================

-- Trigger to create profile on new user registration
-- This trigger fires AFTER INSERT on auth.users
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();

-- The handle_new_user function (defined in public schema):
-- CREATE OR REPLACE FUNCTION public.handle_new_user()
-- RETURNS trigger
-- LANGUAGE plpgsql
-- SECURITY DEFINER
-- AS $$
-- BEGIN
--   INSERT INTO public.profiles(id, first_name, last_name, account_code)
--   VALUES(
--     new.id,
--     new.raw_user_meta_data ->> 'first_name',
--     new.raw_user_meta_data ->> 'last_name',
--     new.raw_user_meta_data ->> 'account_code'
--   );
--   RETURN new;
-- END;
-- $$;


-- ============================================================================
-- FOREIGN KEY REFERENCES FROM PUBLIC SCHEMA
-- ============================================================================

-- The following public tables reference auth.users:
--
-- 1. public.profiles
--    CONSTRAINT profiles_id_fkey
--    FOREIGN KEY (id) REFERENCES auth.users(id)
--
-- 2. public.projects
--    CONSTRAINT projects_user_id_fkey
--    FOREIGN KEY (user_id) REFERENCES auth.users(id)
--
-- 3. public.notifications
--    CONSTRAINT notifications_user_id_fkey
--    FOREIGN KEY (user_id) REFERENCES auth.users(id)
--
-- 4. public.device_tokens
--    CONSTRAINT device_tokens_user_id_fkey
--    FOREIGN KEY (user_id) REFERENCES auth.users(id)
--
-- 5. public.requirement_changes
--    CONSTRAINT requirement_changes_changed_by_fkey
--    FOREIGN KEY (changed_by) REFERENCES auth.users(id)
--
-- 6. public.sws2026_blog_authors
--    CONSTRAINT sws2026_blog_authors_user_id_fkey
--    FOREIGN KEY (user_id) REFERENCES auth.users(id)
--
-- 7. public.sws2026_media
--    CONSTRAINT sws2026_media_uploaded_by_fkey
--    FOREIGN KEY (uploaded_by) REFERENCES auth.users(id)


-- ============================================================================
-- AUTH HELPER FUNCTIONS (Available in SQL/RLS)
-- ============================================================================

-- auth.uid() - Returns the current user's UUID
-- Usage: auth.uid() in RLS policies
-- Example: USING (user_id = auth.uid())

-- auth.role() - Returns the current user's role ('anon', 'authenticated', etc.)
-- Usage: auth.role() in RLS policies
-- Example: USING (auth.role() = 'authenticated')

-- auth.email() - Returns the current user's email
-- Usage: auth.email()

-- auth.jwt() - Returns the full JWT claims as JSON
-- Usage: auth.jwt() -> 'claim_name'


-- ============================================================================
-- BEST PRACTICES FOR AUTH SCHEMA
-- ============================================================================

-- 1. NEVER modify auth tables directly
--    - Use Supabase Auth API for user management
--    - Use Dashboard for configuration changes

-- 2. Use triggers for extending auth behavior
--    - Example: on_auth_user_created trigger creates profiles

-- 3. Use RLS policies with auth functions
--    - auth.uid() for user-specific access
--    - auth.role() for role-based access

-- 4. Store additional user data in public.profiles
--    - Keep auth.users clean
--    - Add custom fields to profiles table

-- 5. Use Edge Functions for custom auth flows
--    - Custom verification logic
--    - Third-party integrations
--    - Webhook handlers


-- ============================================================================
-- SUPABASE AUTH CONFIGURATION
-- ============================================================================

-- The following settings are configured in Supabase Dashboard:
--
-- Auth Settings:
-- - Site URL
-- - Redirect URLs
-- - JWT Secret & Expiry
-- - Password requirements
--
-- Email Settings:
-- - SMTP configuration
-- - Email templates
-- - Confirmation required
--
-- Providers:
-- - Email/Password
-- - Magic Link
-- - Phone (SMS)
-- - Social providers (Google, GitHub, etc.)
--
-- Security:
-- - CAPTCHA
-- - Rate limiting
-- - Session management
